### ISSUE TITLE
pacinfo --short segfaults

### ISSUE THREAD

**Issue by AladW** [andrewgregory/pacutils#10]
```
(gdb) run --short < pacsift
Starting program: /usr/bin/pacinfo --short < pacsift
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
custom/acroread 9.5.5-5
    Adobe Reader is a PDF file viewer
custom/agetpkg-git 2.r0.g56f5023-6 [installed]
    Archlinux Archive Get Package (Git version)
custom/alpine 2.20-3
    Apache licensed PINE mail user agent
custom/alternating-layouts-git r24.da6584a-1
    Alternating split directions for the i3-wm
custom/aria2-git 1.22.0.27.g94a45bf-1 [installed]
    Download utility that supports HTTP(S), FTP, BitTorrent, and Metalink
custom/asciinema 1.2.0-2 [installed]
    Record and share your terminal sessions, the right way
custom/asp-git r49.b91a953-1 [installed]
    Arch Linux build source file management (git version)
custom/aurdupes 1.0-1 [installed]
    Uses your local pacman repos and an AUR package list to find duplicate packages.
custom/aurutils 0.8.4-1
    helper tools for the arch user repository
custom/aws-cli 1.10.23-1
    Universal Command Line Interface for Amazon Web Services awscli
custom/base-config 20160115-6 [installed]

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt full
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
No locals.
#1  0x00007ffff766159f in __GI__IO_fputs (str=0x0, fp=fp@entry=0x7ffff7995600 <_IO_2_1_stdout_>) at iofputs.c:33
        len = <optimized out>
        result = <optimized out>
#2  0x0000000000402b60 in print_pkg_info (pkg=0x61c2c0) at pacinfo.c:285
        db = 0x60b0f0
        localdb = 0x605460
#3  0x0000000000402c78 in print_pkgspec_info (pkgspec=0x60b4d0 "custom/base-config") at pacinfo.c:353
        i = 0x6079e0
        pkgs = <optimized out>
#4  0x0000000000401e25 in main (argc=<optimized out>, argv=0x7fffffffe7d8) at pacinfo.c:390
        buf = 0x60b4d0 "custom/base-config"
        len = 120
        read = <optimized out>
        ret = 0
(gdb)
```
Input file: https://ptpb.pw/rVqv
Database files as in #9

**Comment by AladW** [comment]
It segfaults on a package without description:

https://ptpb.pw/jD-e
https://ptpb.pw/0TzI

**Comment by andrewgregory** [comment]
Does 96fa089762b92135135ed0e20a669af019ca2893 fix this?

**Comment by AladW** [comment]
Yep, I can't reproduce it with the above commit. Thanks
